#!/usr/bin/env python3
"""Run the Dune whale-wallet pipeline end to end.

Two phases:

  tokens  Runs 01_token_universe.sql, writes the OG $100M+ token list.
  whales  Injects those mints into 06_whale_wallets.sql, writes the wallet list.
  all     Both, in order.

The wallet list lands in out/wallets.txt (one address per line) plus a CSV with
the supporting numbers.

Auth: set DUNE_API_KEY in the environment, or pass --api-key. The key is never
written to disk and out/ is gitignored.

Creating queries via the API needs a Dune Analyst plan or higher. On a lower
plan, save the SQL as queries in the Dune UI and pass --universe-query-id /
--whale-query-id so the script executes those instead of creating its own.

Stdlib only — no pip install needed.
"""

import argparse
import csv
import json
import os
import re
import ssl
import sys
import time
import urllib.error
import urllib.parse
import urllib.request

API = "https://api.dune.com/api/v1"
ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
QUERY_DIR = os.path.join(ROOT, "queries")
OUT_DIR = os.path.join(ROOT, "out")
STATE_FILE = os.path.join(OUT_DIR, "query_ids.json")

# Tokens that clear a $100M market cap but are not what we are looking for:
# staked-SOL derivatives, stables, bridged majors and infra/governance tokens.
DEFAULT_EXCLUDE = [
    "SOL", "WSOL", "MSOL", "JITOSOL", "BSOL", "JUPSOL", "INF", "HSOL", "JSOL",
    "USDC", "USDT", "USDS", "USDE", "PYUSD", "USDY", "FDUSD", "EURC", "USD1",
    "WBTC", "CBBTC", "ZBTC", "WETH", "ETH", "USDH",
    "JUP", "JTO", "PYTH", "RAY", "ORCA", "W", "DRIFT", "KMNO", "CLOUD",
    "RENDER", "RNDR", "HNT", "MOBILE", "IOT", "SHDW", "MPLX", "METAPLEX",
]


class DuneError(RuntimeError):
    pass


def _ssl_context():
    """Trust the agent proxy's CA bundle when one is configured."""
    for candidate in (
        os.environ.get("SSL_CERT_FILE"),
        os.environ.get("REQUESTS_CA_BUNDLE"),
        "/root/.ccr/ca-bundle.crt",
    ):
        if candidate and os.path.exists(candidate):
            return ssl.create_default_context(cafile=candidate)
    return ssl.create_default_context()


def _request(method, path, key, body=None, timeout=120):
    url = f"{API}{path}"
    data = json.dumps(body).encode() if body is not None else None
    req = urllib.request.Request(url, data=data, method=method)
    req.add_header("X-DUNE-API-KEY", key)
    req.add_header("Accept", "application/json")
    if data is not None:
        req.add_header("Content-Type", "application/json")
    try:
        with urllib.request.urlopen(req, timeout=timeout, context=_ssl_context()) as resp:
            return json.loads(resp.read().decode())
    except urllib.error.HTTPError as exc:
        detail = exc.read().decode(errors="replace")[:600]
        if exc.code in (402, 403):
            detail += (
                "\n\nIf this is the create-query call, your plan does not allow it. "
                "Save the SQL as a query in the Dune UI and rerun with "
                "--universe-query-id / --whale-query-id."
            )
        raise DuneError(f"{method} {path} -> HTTP {exc.code}: {detail}") from None
    except urllib.error.URLError as exc:
        raise DuneError(f"{method} {path} -> {exc.reason}") from None


def load_state():
    try:
        with open(STATE_FILE) as fh:
            return json.load(fh)
    except (OSError, ValueError):
        return {}


def save_state(state):
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(STATE_FILE, "w") as fh:
        json.dump(state, fh, indent=2)


def ensure_query(key, slot, name, sql, explicit_id=None):
    """Reuse a saved query when we can; only create one the first time.

    Without this every run would litter the account with near-identical queries.
    """
    if explicit_id:
        _request("PATCH", f"/query/{explicit_id}", key, {"query_sql": sql})
        return int(explicit_id)

    state = load_state()
    query_id = state.get(slot)
    if query_id:
        try:
            _request("PATCH", f"/query/{query_id}", key, {"query_sql": sql})
            return int(query_id)
        except DuneError as exc:
            print(f"  ! could not update saved query {query_id} ({exc}); creating a new one",
                  file=sys.stderr)

    created = _request(
        "POST", "/query", key,
        {"name": name, "description": "Generated by scripts/find_whales.py",
         "query_sql": sql, "is_private": True},
    )
    query_id = created["query_id"]
    state[slot] = query_id
    save_state(state)
    print(f"  created query {query_id} (https://dune.com/queries/{query_id})")
    return int(query_id)


def run_query(key, query_id, performance="medium", poll=15, timeout=2700):
    execution_id = _request(
        "POST", f"/query/{query_id}/execute", key, {"performance": performance}
    )["execution_id"]
    print(f"  execution {execution_id} started ({performance} tier)")

    deadline = time.time() + timeout
    last_state = None
    while time.time() < deadline:
        status = _request("GET", f"/execution/{execution_id}/status", key)
        state = status.get("state")
        if state != last_state:
            print(f"  {state}")
            last_state = state
        if state == "QUERY_STATE_COMPLETED":
            return execution_id
        if state in ("QUERY_STATE_FAILED", "QUERY_STATE_CANCELLED", "QUERY_STATE_EXPIRED"):
            raise DuneError(
                f"execution {execution_id} ended in {state}: "
                f"{status.get('error') or status}"
            )
        time.sleep(poll)
    raise DuneError(f"execution {execution_id} still running after {timeout}s")


def fetch_rows(key, execution_id, page=5000):
    rows, offset = [], 0
    while True:
        payload = _request(
            "GET", f"/execution/{execution_id}/results?limit={page}&offset={offset}", key
        )
        batch = payload.get("result", {}).get("rows", [])
        rows.extend(batch)
        if len(batch) < page:
            return rows
        offset += page


def write_csv(path, rows):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    if not rows:
        open(path, "w").close()
        return
    with open(path, "w", newline="") as fh:
        writer = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        writer.writeheader()
        writer.writerows(rows)


def read_sql(filename):
    with open(os.path.join(QUERY_DIR, filename)) as fh:
        return fh.read()


def phase_tokens(args, key):
    print("[1/2] token universe")
    sql = read_sql("01_token_universe.sql")
    if args.lookback:
        sql = sql.replace("DATE '2024-01-01' AS lookback_start",
                          f"DATE '{args.lookback}' AS lookback_start")
    query_id = ensure_query(key, "universe", "OG Solana memecoin universe (auto)",
                            sql, args.universe_query_id)
    rows = fetch_rows(key, run_query(key, query_id, args.performance))
    write_csv(os.path.join(OUT_DIR, "tokens.csv"), rows)
    print(f"  {len(rows)} tokens cleared the market-cap screen -> out/tokens.csv")

    exclude = {s.strip().upper() for s in args.exclude_symbols.split(",") if s.strip()}
    kept = [r for r in rows if (r.get("symbol") or "").upper() not in exclude]
    kept = kept[: args.top_tokens]

    print(f"\n  keeping the top {len(kept)} after removing LSTs/stables/infra:\n")
    for row in kept:
        mcap = row.get("peak_mcap_usd") or 0
        print(f"    {(row.get('symbol') or '?'):>12}  ${mcap/1e6:>10,.0f}M  {row.get('mint')}")

    with open(os.path.join(OUT_DIR, "universe_mints.json"), "w") as fh:
        json.dump([{"symbol": r.get("symbol"), "mint": r.get("mint")} for r in kept], fh, indent=2)
    return kept


def phase_whales(args, key, tokens):
    print("\n[2/2] whale wallets")
    if not tokens:
        raise DuneError("no tokens in the universe — nothing to search against")

    mint_list = ",\n".join(f"        ('{t['mint']}')" for t in tokens)
    # Compare against the template rather than scanning for the placeholder
    # string, which also appears in that file's header comment.
    template = read_sql("06_whale_wallets.sql")
    sql = template.replace("        ('__MINT_LIST__')", mint_list)
    if sql == template:
        raise DuneError("mint placeholder row not found in 06_whale_wallets.sql")

    replacements = {
        "min_position_usd": args.min_position,
        "min_invested_usd": args.min_invested,
        "min_total_pnl_usd": args.min_pnl,
        "min_pnl_excluding_best_usd": args.min_pnl_excluding_best,
        "min_median_hold_days": args.min_hold_days,
    }
    for name, value in replacements.items():
        if value is None:
            continue
        # Keeps the trailing inline comment on the param line intact.
        sql, count = re.subn(rf"^(\s*)\S+(\s+AS {name}\b.*)$",
                             rf"\g<1>{value}\g<2>", sql, count=1, flags=re.M)
        if count != 1:
            raise DuneError(f"could not override {name} in 06_whale_wallets.sql")
    if args.lookback:
        sql = sql.replace("DATE '2024-01-01' AS lookback_start",
                          f"DATE '{args.lookback}' AS lookback_start")

    if args.dry_run:
        print(sql)
        return []

    query_id = ensure_query(key, "whales", "Solana memecoin whale wallets (auto)",
                            sql, args.whale_query_id)
    rows = fetch_rows(key, run_query(key, query_id, args.performance))

    write_csv(os.path.join(OUT_DIR, "whale_wallets.csv"), rows)
    with open(os.path.join(OUT_DIR, "wallets.txt"), "w") as fh:
        for row in rows:
            fh.write(f"{row['wallet']}\n")

    print(f"\n  {len(rows)} wallets -> out/whale_wallets.csv, out/wallets.txt")
    if rows:
        print(f"\n  {'wallet':<46}{'pnl':>14}{'excl. best':>14}{'wins':>7}{'hold d':>8}")
        for row in rows[:25]:
            print(f"  {row['wallet']:<46}"
                  f"{(row.get('total_pnl_usd') or 0):>14,.0f}"
                  f"{(row.get('pnl_excluding_best_usd') or 0):>14,.0f}"
                  f"{str(row.get('n_profitable_positions')) + '/' + str(row.get('n_positions')):>7}"
                  f"{(row.get('median_hold_days') or 0):>8,.0f}")
    return rows


def main():
    parser = argparse.ArgumentParser(description=__doc__,
                                     formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("phase", nargs="?", default="all", choices=["tokens", "whales", "all"])
    parser.add_argument("--api-key", default=os.environ.get("DUNE_API_KEY"))
    parser.add_argument("--top-tokens", type=int, default=15,
                        help="how many of the biggest memecoins to search across")
    parser.add_argument("--exclude-symbols", default=",".join(DEFAULT_EXCLUDE))
    parser.add_argument("--lookback", default=None, metavar="YYYY-MM-DD")
    parser.add_argument("--performance", default="medium", choices=["medium", "large"])
    parser.add_argument("--min-position", type=int, default=None,
                        help="minimum USD bought in a single token to count as a position")
    parser.add_argument("--min-invested", type=int, default=None)
    parser.add_argument("--min-pnl", type=int, default=None)
    parser.add_argument("--min-pnl-excluding-best", type=int, default=None,
                        help="PnL ignoring the single best position — the repeat-winner gate")
    parser.add_argument("--min-hold-days", type=int, default=None)
    parser.add_argument("--universe-query-id", default=None)
    parser.add_argument("--whale-query-id", default=None)
    parser.add_argument("--dry-run", action="store_true",
                        help="print the whale SQL with mints injected, run nothing")
    args = parser.parse_args()

    if not args.api_key and not args.dry_run:
        parser.error("no API key: set DUNE_API_KEY or pass --api-key")

    os.makedirs(OUT_DIR, exist_ok=True)
    try:
        tokens = []
        if args.phase in ("tokens", "all"):
            tokens = phase_tokens(args, args.api_key)
        elif args.phase == "whales":
            with open(os.path.join(OUT_DIR, "universe_mints.json")) as fh:
                tokens = json.load(fh)

        if args.phase in ("whales", "all"):
            phase_whales(args, args.api_key, tokens)
    except DuneError as exc:
        print(f"\nerror: {exc}", file=sys.stderr)
        return 1
    except FileNotFoundError:
        print("\nerror: run the `tokens` phase first — out/universe_mints.json is missing",
              file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
